# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/hgfs/programmerGrowPlan/emlib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/hgfs/programmerGrowPlan/emlib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/hgfs/programmerGrowPlan/emlib/CMakeFiles /mnt/hgfs/programmerGrowPlan/emlib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/hgfs/programmerGrowPlan/emlib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named emlib

# Build rule for target.
emlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 emlib
.PHONY : emlib

# fast build rule for target.
emlib/fast:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/build
.PHONY : emlib/fast

src/lock.o: src/lock.c.o

.PHONY : src/lock.o

# target to build an object file
src/lock.c.o:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/lock.c.o
.PHONY : src/lock.c.o

src/lock.i: src/lock.c.i

.PHONY : src/lock.i

# target to preprocess a source file
src/lock.c.i:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/lock.c.i
.PHONY : src/lock.c.i

src/lock.s: src/lock.c.s

.PHONY : src/lock.s

# target to generate assembly for a file
src/lock.c.s:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/lock.c.s
.PHONY : src/lock.c.s

src/log.o: src/log.c.o

.PHONY : src/log.o

# target to build an object file
src/log.c.o:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/log.c.o
.PHONY : src/log.c.o

src/log.i: src/log.c.i

.PHONY : src/log.i

# target to preprocess a source file
src/log.c.i:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/log.c.i
.PHONY : src/log.c.i

src/log.s: src/log.c.s

.PHONY : src/log.s

# target to generate assembly for a file
src/log.c.s:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/log.c.s
.PHONY : src/log.c.s

src/nest_lock.o: src/nest_lock.c.o

.PHONY : src/nest_lock.o

# target to build an object file
src/nest_lock.c.o:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/nest_lock.c.o
.PHONY : src/nest_lock.c.o

src/nest_lock.i: src/nest_lock.c.i

.PHONY : src/nest_lock.i

# target to preprocess a source file
src/nest_lock.c.i:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/nest_lock.c.i
.PHONY : src/nest_lock.c.i

src/nest_lock.s: src/nest_lock.c.s

.PHONY : src/nest_lock.s

# target to generate assembly for a file
src/nest_lock.c.s:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/nest_lock.c.s
.PHONY : src/nest_lock.c.s

src/pthread_lock.o: src/pthread_lock.c.o

.PHONY : src/pthread_lock.o

# target to build an object file
src/pthread_lock.c.o:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/pthread_lock.c.o
.PHONY : src/pthread_lock.c.o

src/pthread_lock.i: src/pthread_lock.c.i

.PHONY : src/pthread_lock.i

# target to preprocess a source file
src/pthread_lock.c.i:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/pthread_lock.c.i
.PHONY : src/pthread_lock.c.i

src/pthread_lock.s: src/pthread_lock.c.s

.PHONY : src/pthread_lock.s

# target to generate assembly for a file
src/pthread_lock.c.s:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/pthread_lock.c.s
.PHONY : src/pthread_lock.c.s

src/pthread_nest_lock.o: src/pthread_nest_lock.c.o

.PHONY : src/pthread_nest_lock.o

# target to build an object file
src/pthread_nest_lock.c.o:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/pthread_nest_lock.c.o
.PHONY : src/pthread_nest_lock.c.o

src/pthread_nest_lock.i: src/pthread_nest_lock.c.i

.PHONY : src/pthread_nest_lock.i

# target to preprocess a source file
src/pthread_nest_lock.c.i:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/pthread_nest_lock.c.i
.PHONY : src/pthread_nest_lock.c.i

src/pthread_nest_lock.s: src/pthread_nest_lock.c.s

.PHONY : src/pthread_nest_lock.s

# target to generate assembly for a file
src/pthread_nest_lock.c.s:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/src/pthread_nest_lock.c.s
.PHONY : src/pthread_nest_lock.c.s

test/main.o: test/main.c.o

.PHONY : test/main.o

# target to build an object file
test/main.c.o:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/test/main.c.o
.PHONY : test/main.c.o

test/main.i: test/main.c.i

.PHONY : test/main.i

# target to preprocess a source file
test/main.c.i:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/test/main.c.i
.PHONY : test/main.c.i

test/main.s: test/main.c.s

.PHONY : test/main.s

# target to generate assembly for a file
test/main.c.s:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/test/main.c.s
.PHONY : test/main.c.s

test/pthread_mutex.o: test/pthread_mutex.c.o

.PHONY : test/pthread_mutex.o

# target to build an object file
test/pthread_mutex.c.o:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/test/pthread_mutex.c.o
.PHONY : test/pthread_mutex.c.o

test/pthread_mutex.i: test/pthread_mutex.c.i

.PHONY : test/pthread_mutex.i

# target to preprocess a source file
test/pthread_mutex.c.i:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/test/pthread_mutex.c.i
.PHONY : test/pthread_mutex.c.i

test/pthread_mutex.s: test/pthread_mutex.c.s

.PHONY : test/pthread_mutex.s

# target to generate assembly for a file
test/pthread_mutex.c.s:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/test/pthread_mutex.c.s
.PHONY : test/pthread_mutex.c.s

test/test.o: test/test.c.o

.PHONY : test/test.o

# target to build an object file
test/test.c.o:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/test/test.c.o
.PHONY : test/test.c.o

test/test.i: test/test.c.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.c.i:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/test/test.c.i
.PHONY : test/test.c.i

test/test.s: test/test.c.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.c.s:
	$(MAKE) -f CMakeFiles/emlib.dir/build.make CMakeFiles/emlib.dir/test/test.c.s
.PHONY : test/test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... emlib"
	@echo "... src/lock.o"
	@echo "... src/lock.i"
	@echo "... src/lock.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/nest_lock.o"
	@echo "... src/nest_lock.i"
	@echo "... src/nest_lock.s"
	@echo "... src/pthread_lock.o"
	@echo "... src/pthread_lock.i"
	@echo "... src/pthread_lock.s"
	@echo "... src/pthread_nest_lock.o"
	@echo "... src/pthread_nest_lock.i"
	@echo "... src/pthread_nest_lock.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
	@echo "... test/pthread_mutex.o"
	@echo "... test/pthread_mutex.i"
	@echo "... test/pthread_mutex.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

